{{- if .Values.secrets.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "ideal-service.fullname" . }}
  labels:
    {{- include "ideal-service.labels" . | nindent 4 }}
spec:
  encryptedData:
    CONNECTION_STRING: {{ .Values.secrets.encryptedConnectionString | quote }}
  template:
    metadata:
      name: {{ include "ideal-service.fullname" . }}
      labels:
        {{- include "ideal-service.labels" . | nindent 8 }}
    type: Opaque
{{- end -}}
