{{- if .Values.secrets.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "ideal-service.fullname" . }}
  labels:
    {{- include "ideal-service.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- if .Values.secrets.encryptedConnectionString }}
    CONNECTION_STRING: {{ .Values.secrets.encryptedConnectionString | quote }}
    {{- end }}
    {{- if .Values.secrets.encryptedPostgresPassword }}
    postgres-password: {{ .Values.secrets.encryptedPostgresPassword | quote }}
    password: {{ .Values.secrets.encryptedPostgresPassword | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ include "ideal-service.fullname" . }}
      labels:
        {{- include "ideal-service.labels" . | nindent 8 }}
    type: Opaque
{{- end -}}
