image:
  tag: "1.5.1"
replicaCount: 1

secrets:
  enabled: true
  encryptedPostgresPassword: "AgDC5Jd4ulsYxyFG8zrIr8QKsNalGwPOyHc9hDaWzhki7JWMaZZH6nuzv8tsaT4XCnRKc0/8MunW7mZHbvasIykGkSpdCU88ecXZpnLDG7g04rK+d6h9zkwFdbJ9ZBVufTL5g4mEU6KOsZJmA3PX9g4DhhuDQSCGZOEu64c2Nmq+HyF7Wj2o9lFkir6cjjHIA+ScgzQGXz1R6255e4sSb8kbpHTSfndEuPObyPpRmHIQEtxSX7aXSlJHl+87gSRuzURrEyUrqCpzYN3o9iF+kkY7AupaSiYvQSYj+OxvnMVKTD5U2slQhxvriMDlnGDO4xY2wNa4yUeGqwaFDX+P/Q+CCFiEjl+1Qj/tPoV3PfLjwPw3r6Gvwf7Npbb3fsNobyEH8SKwtyVEjOTIhbHHarAEmP/ThvI1FRpyxzICLrfQGI91H5PnKiB9K8N9+vKD+gkIG7JW/VL7x5AIn+KGK78A68OA7HGHxTKncTnyCI33bJxFiEpEoLWnCuh9To2/t5lkJvlukPn0QbANFvLu9DnVz+14GQqYvlYlO+Z4a/hnqTjaAeW+XNC7GBfxgsS61t7Dg+0DdqSsmb6AropDfJQB5CAVfcuEyty27QIuoFCRV1uROU/gO0yYac+wyreOy70ScXPYEQD4kLYykebc0567PZtY8v5u7NjRC8TpUSjM29fVJqYfPtXaI47rMb9egz6zlf42+8nYhP2Rd12FDQ=="
