name: PR Validation

on:
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - 'manifests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '8.0.x'

      - name: Run Tests
        run: dotnet test src/IdealService.Tests/IdealService.Tests.csproj -c Release
